version: '3.9'

services:
  # Database service
  database:
    image: postgres:latest
    ports:
      - "${DB_PUBLIC_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  # Web API service
  webapi:
    image: finance-helper
    ports:
      - "${WEBAPI_PUBLIC_PORT}:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ConnectionStrings:DatabaseConnection=host=${DATABASE_HOST};port=5432;database=${DB_NAME};username=${DB_USER};password=${DB_PASSWORD}
      # Swagger
      - SwaggerDocOptions:Title=Finance-Helper API
      - SwaggerDocOptions:Description=Application to help people manage their finances
      - SwaggerDocOptions:Organization=Ermakov Egor
      - Email:Organization=egor4yt@gmail.com
      - CorsOrigins=${CORS_ORIGINS}